routing
krogulex/home-budget pull request #14
Opened 2023-06-13 11:04 UTC by krogulex

Done basic routing

2023-06-13 12:24 UTC, Asgrim98 requested changes
Zmianki

2023-06-13 12:24 UTC, Asgrim98 commented on frontend/package.json
> +    "react-router-dom": "^6.12.1",
Takim importy są automatyczne ale też potencjalnie niebezpieczne. Ponieważ:

1. Nie wiesz czy to jest teraz wersja 6.12.1 czy jakaś nowsza
2. Jak ktoś później zainstaluje te pakiety to może być tak, że zainstaluje mu zupełnie nowy pakiet nowszych wersji gdzie coś może nie być kompatybilne wstecz. 

Tak więc najlepiej usunąć to "^" i zostawić konkretną wersję.

Jednak małe ale bo nie wiesz teraz jaka jest u Cb zainstalowana. Podczas instalowania npm też wyszukuje kompatybilne ze sobą wersję czyli np. react-dom 18.2.0 działa jedynie z react-router-dom 6.13.1 wiec Ci zainstaluje taką konretną pierwszą kombinacje wersji gdzie to zadziała bez problemów. Wiec używanie ^ jest szybsze i nie powoduje błędów. Ale jak już Ci się poinstalowało wszystko to możesz zrobić

`npm list` lub zmienić wersję tego pakietu z `^6.12.1` na np. `7.0.0` i wtedy środowisko powinno Ci krzyknąć ze nie masz tej wersji w node_modules i potrzeba npm install. 

Więc proponuje po prostu pozmieniać te wersje na konkretne dzięki czemu później nie będzie potencjalnych problemów.

2023-06-13 12:24 UTC, Asgrim98 commented on package-lock.json
> +  "name": "home-budget",
Ten pliczek to nie wiem skąd się wziął ale raczej go nie powinno tutaj być. Pewnie zrobiłes jakiś npm install w głównym katalogu i się dodał.

2023-06-13 12:24 UTC, Asgrim98 commented on frontend/src/Pages/Registration.tsx
> +    return ( <div>Registration page</div> );
Generalnie to wydaje mi się, że nie masz tutaj zformatowanego kodu. Dodaj może jakiś eslint np. z prettierem.

Możesz sobie tam skopiować pliki i importy potrzebne z backendu (żeby było to samo). I też możesz dodać taką komendę co jest w backendzie 

```json
"format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
"lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
```
Tylko tam podmień na tsx lub dodaj nowe w zależności jakie pliki będziecie mieć itd.

PS Na tym branchu backend jeszcze nie jest sformatowany więc nie sugeruj się tym, że tam są jakieś błędy. To zostanie poprawione jak wypuszczę auth. Wtedy będzie ładnie :)

2023-06-13 15:37 UTC, krogulex commented on frontend/src/Pages/Registration.tsx
> +interface RegistrationProps {
Korzystałem z formatki "Function Component (Simple React Snippets)"

2023-06-13 15:43 UTC, krogulex commented on frontend/package.json
> +    "react-router-dom": "^6.12.1",
Słuszna sprawa, nawet nie zwracałem na to zbytnio uwagi. ;)

2023-06-13 17:14 UTC, UlEdy approved these changes

2023-06-13 17:19 UTC, Asgrim98 commented on frontend/package-lock.json
>          "web-vitals": "^2.1.4"
Korzystamy z konkretnych wersji dependencji więc każdy będzie miał to samo w tym pliki tak czy inaczej. Jednak często commitowanie tego pliczku (jest on bardzo duży) powoduje problemy z rozwiązywaniu potencjalnych konflików. Wiec w wersji devowej imo nie ma sensu go trzymać. Jak byśmy korzystali później deployowali to na produkcje to można to dorzucić. Jednak np. jak to będziemy mergować do mastera.

2023-06-14 12:02 UTC, krogulex commented on frontend/package-lock.json
>          "web-vitals": "^2.1.4"
oki

2023-06-14 12:03 UTC, merged